<?php


namespace api\modules\shop\forms;


use api\modules\shop\models\OrderGoods;

class OrderGoodsForm extends OrderGoods
{
    /**
     * @return array|array[]
     */
    public function rules()
    {
        return [
            [['shop_id', 'order_id', 'goods_id', 'name', 'unit', 'purchase_price', 'price', 'book_num', 'format'], 'required'],
            [['product_date', 'shelf_life', 'number', 'remark'], 'default', 'value' => '']
        ];
    }

    /**
     * @return array|array[]
     */
    public function scenarios()
    {
        return array_merge(parent::scenarios(), [
            self::SCENARIO_STORE => ['shop_id', 'order_id', 'goods_id', 'name', 'number', 'unit', 'purchase_price', 'price', 'book_num', 'format', 'product_date', 'shelf_life', 'remark']
        ]); // TODO: Change the autogenerated stub
    }
}
